name: Deploy to Simply.com      

on: 
  push:
    branches:
      - main    


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Deploy to Simply.com
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        username: ${{ secrets.FTP SERVER }}
        password: ${{ secrets.FTP_USERNAME }}
        domain: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: cerestrattoria/